site_name: Image Mode Security and Compliance
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Introduction: modules/module-01-introduction.md
  - Module 2 - Adding Security Controls: modules/module-02-adding-security-controls.md
  - Module 3 - Testing Compliance: modules/module-03-testing-compliance.md
plugins:
- techdocs-core
